New shield code
AndroidQuazar/VanillaFactionsExpanded-Core pull request #4
Opened 2020-08-25 00:02 UTC by Taranchuk

2020-08-25 00:09 UTC, Taranchuk commented
New changes:

Shields are now counted as apparel instead of equipment. This is done so that we can draw them in the apparel class, instead of in the pavn renderer transpiler. If possible, additional patches can be made to virtually place them in the equipment section.

Removed stats worker patch. As it turned out, it does not affect armor stats at all, it handles in a separate patch. Still not fully understood the purpose of this patch, but the combat is still unchanged after the removal of this stats worker patch.

There are changes in the medieval mod, we need to put this xml block:
```
		<thingClass>VFECore.Apparel_Shield</thingClass>
		<apparel>
			<bodyPartGroups>
				<li>LeftHand</li>
			</bodyPartGroups>
			<layers>
				<li>VFEC_OuterShell</li>
			</layers>
		</apparel>
```
into <ThingDef Name="VFEM_BaseShield"

2020-08-25 00:10 UTC, Taranchuk commented
Otherwise everything is unchanged, no functionality has been removed or altered

2020-08-25 00:31 UTC, erdelf requested changes
Code in general needs a partial rewrite, but for conversion to apparel seems good.
(Didn't manually check if the drawloc checks out)

2020-08-25 00:31 UTC, erdelf commented on Source/VFECore/HarmonyPatches/HarmonyPatches.cs
> +                //var humanBipedDrawer = GenTypes.GetTypeInAnyAssembly("FacialStuff.HumanBipedDrawer", "FacialStuff");
this whole section is not required anymore, due to moving out of the pawn renderer I take it. Remove if so.

2020-08-25 00:31 UTC, erdelf commented on Source/VFECore/Utilities/ShieldUtility.cs
> +        public static void AddShield(this Pawn_EquipmentTracker equipment, ThingWithComps newEq, Pawn wearer)
Is there any advantage to giving both equipment tracker and wearer, given the usage seems to imply the equipment tracker is of the wearer ?

2020-08-25 00:31 UTC, erdelf commented on Source/VFECore/Apparels/Apparel_Shield.cs
> +        private Vector3 GetAimingVector(Vector3 rootLoc)
a whole lot of magic numbers in this method. Would benefit from a few comments.

2020-08-25 03:15 UTC, Taranchuk commented on Source/VFECore/Utilities/ShieldUtility.cs
> +        public static void AddShield(this Pawn_EquipmentTracker equipment, ThingWithComps newEq, Pawn wearer)
i changed the method in new commits so it now uses the wearer

2020-08-25 03:16 UTC, Taranchuk commented on Source/VFECore/Apparels/Apparel_Shield.cs
> +        private Vector3 GetAimingVector(Vector3 rootLoc)
these numbers are from vanilla DrawEquipment method

2020-08-25 03:16 UTC, Taranchuk commented on Source/VFECore/HarmonyPatches/HarmonyPatches.cs
> +                //var humanBipedDrawer = GenTypes.GetTypeInAnyAssembly("FacialStuff.HumanBipedDrawer", "FacialStuff");
done

2020-08-25 12:08 UTC, merged

2020-08-28 03:56 UTC, lbmaian commented
> Removed stats worker patch. As it turned out, it does not affect armor stats at all, it handles in a separate patch. Still not fully understood the purpose of this patch, but the combat is still unchanged after the removal of this stats worker patch.

@Taranchuk It's for adding stat modifiers for non-shield/armor-related stats like a move speed modifier, e.g.

```xml
		<equippedStatOffsets>
			<ShootingAccuracyPawn>-0.1</ShootingAccuracyPawn>
			<MoveSpeed>-0.5</MoveSpeed>
		</equippedStatOffsets>
```

With your change to make shields part of apparel, this isn't needed anymore, since stat modifiers from worn apparel are automatically considered in StatsWorker. The patch was only necessary for equipment because StatsWorker only looked at the primary equipment.

I've also considered making a similar change in JecsTools (making shields apparel and/or removing StatsWorker patch), which shares ChJeez Pawn Shields heritage with this mod, for performance reasons, but thought it would be too much of a breaking change for legacy framework, especially since some JecsTools shields are also weapons.